{"quote": "\u201cIt is our choices, Harry, that show what we truly are, far more than our abilities.\u201d", "author": "J.K. Rowling", "author_url": "https://quotes.toscrape.com/author/J-K-Rowling", "dob": "July 31, 1965"}
{"quote": "\u201cI have not failed. I've just found 10,000 ways that won't work.\u201d", "author": "Thomas A. Edison", "author_url": "https://quotes.toscrape.com/author/Thomas-A-Edison", "dob": "February 11, 1847"}
{"quote": "\u201cImperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.\u201d", "author": "Marilyn Monroe", "author_url": "https://quotes.toscrape.com/author/Marilyn-Monroe", "dob": "June 01, 1926"}
{"quote": "\u201cIt is better to be hated for what you are than to be loved for what you are not.\u201d", "author": "Andr\u00e9 Gide", "author_url": "https://quotes.toscrape.com/author/Andre-Gide", "dob": "November 22, 1869"}
{"quote": "\u201cA day without sunshine is like, you know, night.\u201d", "author": "Steve Martin", "author_url": "https://quotes.toscrape.com/author/Steve-Martin", "dob": "August 14, 1945"}
{"quote": "\u201cYou may not be her first, her last, or her only. She loved before she may love again. But if she loves you now, what else matters? She's not perfect\u2014you aren't either, and the two of you may never be perfect together but if she can make you laugh, cause you to think twice, and admit to being human and making mistakes, hold onto her and give her the most you can. She may not be thinking about you every second of the day, but she will give you a part of her that she knows you can break\u2014her heart. So don't hurt her, don't change her, don't analyze and don't expect more than she can give. Smile when she makes you happy, let her know when she makes you mad, and miss her when she's not there.\u201d", "author": "Bob Marley", "author_url": "https://quotes.toscrape.com/author/Bob-Marley", "dob": "February 06, 1945"}
{"quote": "\u201cThe opposite of love is not hate, it's indifference. The opposite of art is not ugliness, it's indifference. The opposite of faith is not heresy, it's indifference. And the opposite of life is not death, it's indifference.\u201d", "author": "Elie Wiesel", "author_url": "https://quotes.toscrape.com/author/Elie-Wiesel", "dob": "September 30, 1928"}
{"quote": "\u201cA woman is like a tea bag; you never know how strong it is until it's in hot water.\u201d", "author": "Eleanor Roosevelt", "author_url": "https://quotes.toscrape.com/author/Eleanor-Roosevelt", "dob": "October 11, 1884"}
{"quote": "\u201cI may not have gone where I intended to go, but I think I have ended up where I needed to be.\u201d", "author": "Douglas Adams", "author_url": "https://quotes.toscrape.com/author/Douglas-Adams", "dob": "March 11, 1952"}
{"quote": "\u201cLife is what happens to us while we are making other plans.\u201d", "author": "Allen Saunders", "author_url": "https://quotes.toscrape.com/author/Allen-Saunders", "dob": "April 24, 1899"}
{"quote": "\u201cGood friends, good books, and a sleepy conscience: this is the ideal life.\u201d", "author": "Mark Twain", "author_url": "https://quotes.toscrape.com/author/Mark-Twain", "dob": "November 30, 1835"}
{"quote": "\u201cI like nonsense, it wakes up the brain cells. Fantasy is a necessary ingredient in living.\u201d", "author": "Dr. Seuss", "author_url": "https://quotes.toscrape.com/author/Dr-Seuss", "dob": "March 02, 1904"}
{"quote": "\u201cThe world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.\u201d", "author": "Albert Einstein", "author_url": "https://quotes.toscrape.com/author/Albert-Einstein", "dob": "March 14, 1879"}
{"quote": "\u201cIt is not a lack of love, but a lack of friendship that makes unhappy marriages.\u201d", "author": "Friedrich Nietzsche", "author_url": "https://quotes.toscrape.com/author/Friedrich-Nietzsche", "dob": "October 15, 1844"}
{"quote": "\u201cAnyone who thinks sitting in church can make you a Christian must also think that sitting in a garage can make you a car.\u201d", "author": "Garrison Keillor", "author_url": "https://quotes.toscrape.com/author/Garrison-Keillor", "dob": "August 07, 1942"}
{"quote": "\u201cIf you judge people, you have no time to love them.\u201d", "author": "Mother Teresa", "author_url": "https://quotes.toscrape.com/author/Mother-Teresa", "dob": "August 26, 1910"}
{"quote": "\u201cBeauty is in the eye of the beholder and it may be necessary from time to time to give a stupid or misinformed beholder a black eye.\u201d", "author": "Jim Henson", "author_url": "https://quotes.toscrape.com/author/Jim-Henson", "dob": "September 24, 1936"}
{"quote": "\u201cAll you need is love. But a little chocolate now and then doesn't hurt.\u201d", "author": "Charles M. Schulz", "author_url": "https://quotes.toscrape.com/author/Charles-M-Schulz", "dob": "November 26, 1922"}
{"quote": "\u201cI have always imagined that Paradise will be a kind of library.\u201d", "author": "Jorge Luis Borges", "author_url": "https://quotes.toscrape.com/author/Jorge-Luis-Borges", "dob": "August 24, 1899"}
{"quote": "\u201cWe read to know we're not alone.\u201d", "author": "William Nicholson", "author_url": "https://quotes.toscrape.com/author/William-Nicholson", "dob": "January 12, 1948"}
{"quote": "\u201cFor every minute you are angry you lose sixty seconds of happiness.\u201d", "author": "Ralph Waldo Emerson", "author_url": "https://quotes.toscrape.com/author/Ralph-Waldo-Emerson", "dob": "May 25, 1803"}
{"quote": "\u201cI love you without knowing how, or when, or from where. I love you simply, without problems or pride: I love you in this way because I do not know any other way of loving but this, in which there is no I or you, so intimate that your hand upon my chest is my hand, so intimate that when I fall asleep your eyes close.\u201d", "author": "Pablo Neruda", "author_url": "https://quotes.toscrape.com/author/Pablo-Neruda", "dob": "July 12, 1904"}
{"quote": "\u201cThe person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.\u201d", "author": "Jane Austen", "author_url": "https://quotes.toscrape.com/author/Jane-Austen", "dob": "December 16, 1775"}
{"quote": "\u201cIt is never too late to be what you might have been.\u201d", "author": "George Eliot", "author_url": "https://quotes.toscrape.com/author/George-Eliot", "dob": "November 22, 1819"}
{"quote": "\u201cA reader lives a thousand lives before he dies, said Jojen. The man who never reads lives only one.\u201d", "author": "George R.R. Martin", "author_url": "https://quotes.toscrape.com/author/George-R-R-Martin", "dob": "September 20, 1948"}
{"quote": "\u201cYou can never get a cup of tea large enough or a book long enough to suit me.\u201d", "author": "C.S. Lewis", "author_url": "https://quotes.toscrape.com/author/C-S-Lewis", "dob": "November 29, 1898"}
{"quote": "\u201cLove does not begin and end the way we seem to think it does. Love is a battle, love is a war; love is a growing up.\u201d", "author": "James Baldwin", "author_url": "https://quotes.toscrape.com/author/James-Baldwin", "dob": "August 02, 1924"}
{"quote": "\u201cOnly in the darkness can you see the stars.\u201d", "author": "Martin Luther King Jr.", "author_url": "https://quotes.toscrape.com/author/Martin-Luther-King-Jr", "dob": "January 15, 1929"}
{"quote": "\u201cThe difference between genius and stupidity is: genius has its limits.\u201d", "author": "Alexandre Dumas fils", "author_url": "https://quotes.toscrape.com/author/Alexandre-Dumas-fils", "dob": "July 27, 1824"}
{"quote": "\u201cHe's like a drug for you, Bella.\u201d", "author": "Stephenie Meyer", "author_url": "https://quotes.toscrape.com/author/Stephenie-Meyer", "dob": "December 24, 1973"}
{"quote": "\u201cIf you only read the books that everyone else is reading, you can only think what everyone else is thinking.\u201d", "author": "Haruki Murakami", "author_url": "https://quotes.toscrape.com/author/Haruki-Murakami", "dob": "January 12, 1949"}
{"quote": "\u201cWhen one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.\u201d", "author": "Helen Keller", "author_url": "https://quotes.toscrape.com/author/Helen-Keller", "dob": "June 27, 1880"}
{"quote": "\u201cThere is no friend as loyal as a book.\u201d", "author": "Ernest Hemingway", "author_url": "https://quotes.toscrape.com/author/Ernest-Hemingway", "dob": "July 21, 1899"}
{"quote": "\u201cLife isn't about finding yourself. Life is about creating yourself.\u201d", "author": "George Bernard Shaw", "author_url": "https://quotes.toscrape.com/author/George-Bernard-Shaw", "dob": "July 26, 1856"}
{"quote": "\u201cYou don\u2019t forget the face of the person who was your last hope.\u201d", "author": "Suzanne Collins", "author_url": "https://quotes.toscrape.com/author/Suzanne-Collins", "dob": "August 11, 1962"}
{"quote": "\u201cThat's the problem with drinking, I thought, as I poured myself a drink. If something bad happens you drink in an attempt to forget; if something good happens you drink in order to celebrate; and if nothing happens you drink to make something happen.\u201d", "author": "Charles Bukowski", "author_url": "https://quotes.toscrape.com/author/Charles-Bukowski", "dob": "August 16, 1920"}
{"quote": "\u201cNot all those who wander are lost.\u201d", "author": "J.R.R. Tolkien", "author_url": "https://quotes.toscrape.com/author/J-R-R-Tolkien", "dob": "January 03, 1892"}
{"quote": "\u201cIf I had a flower for every time I thought of you...I could walk through my garden forever.\u201d", "author": "Alfred Tennyson", "author_url": "https://quotes.toscrape.com/author/Alfred-Tennyson", "dob": "August 06, 1809"}
{"quote": "\u201cWhat really knocks me out is a book that, when you're all done reading it, you wish the author that wrote it was a terrific friend of yours and you could call him up on the phone whenever you felt like it. That doesn't happen much, though.\u201d", "author": "J.D. Salinger", "author_url": "https://quotes.toscrape.com/author/J-D-Salinger", "dob": "January 01, 1919"}
{"quote": "\u201cThe reason I talk to myself is because I\u2019m the only one whose answers I accept.\u201d", "author": "George Carlin", "author_url": "https://quotes.toscrape.com/author/George-Carlin", "dob": "May 12, 1937"}
{"quote": "\u201cI am free of all prejudice. I hate everyone equally. \u201d", "author": "W.C. Fields", "author_url": "https://quotes.toscrape.com/author/W-C-Fields", "dob": "January 29, 1880"}
{"quote": "\u201cThe question isn't who is going to let me; it's who is going to stop me.\u201d", "author": "Ayn Rand", "author_url": "https://quotes.toscrape.com/author/Ayn-Rand", "dob": "February 02, 1905"}
{"quote": "\u201cYou may say I'm a dreamer, but I'm not the only one. I hope someday you'll join us. And the world will live as one.\u201d", "author": "John Lennon", "author_url": "https://quotes.toscrape.com/author/John-Lennon", "dob": "October 09, 1940"}
{"quote": "\u201cThe trouble with having an open mind, of course, is that people will insist on coming along and trying to put things in it.\u201d", "author": "Terry Pratchett", "author_url": "https://quotes.toscrape.com/author/Terry-Pratchett", "dob": "April 28, 1948"}
{"quote": "\u201cIt takes courage to grow up and become who you really are.\u201d", "author": "E.E. Cummings", "author_url": "https://quotes.toscrape.com/author/E-E-Cummings", "dob": "October 14, 1894"}
{"quote": "\u201cTo die will be an awfully big adventure.\u201d", "author": "J.M. Barrie", "author_url": "https://quotes.toscrape.com/author/J-M-Barrie", "dob": "May 09, 1860"}
{"quote": "\u201cBut better to get hurt by the truth than comforted with a lie.\u201d", "author": "Khaled Hosseini", "author_url": "https://quotes.toscrape.com/author/Khaled-Hosseini", "dob": "March 04, 1965"}
{"quote": "\u201cI'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.\u201d", "author": "Jimi Hendrix", "author_url": "https://quotes.toscrape.com/author/Jimi-Hendrix", "dob": "November 27, 1942"}
{"quote": "\u201cYou have to write the book that wants to be written. And if the book will be too difficult for grown-ups, then you write it for children.\u201d", "author": "Madeleine L'Engle", "author_url": "https://quotes.toscrape.com/author/Madeleine-LEngle", "dob": "November 29, 1918"}
{"quote": "\u201cYou never really understand a person until you consider things from his point of view... Until you climb inside of his skin and walk around in it.\u201d", "author": "Harper Lee", "author_url": "https://quotes.toscrape.com/author/Harper-Lee", "dob": "April 28, 1926"}
